### ISSUE TITLE
Main page UI

### ISSUE THREAD

**Issue by ProdamGaraj** [MindAsEngine/twg-frontend#3]
Создать вёрстку главной страницы сайта с основными элементами типа: "хедер", "футер","компонент". Сделать вёрстку адаптивной с самого начала, продумать отображение на разных экранах (мобильный, планшет, компьютер).

**Comment by ProdamGaraj** [comment]
Не забыть про изменение размеров шрифтов при изменении масштаба страницы.

**Comment by perfectiones** [comment]
Ваня: renew header, блок авторские туры
Рома: О нас
